"""Within-engine A/B for the SHORT contract cap. Same script, same bars, same
window, same flags — ONE variable changes: srp.SHORT_MAX_CONTRACTS.

Method rule this exists to obey (CLAUDE.md, Aug 24 2026): gate a change on a
within-engine A/B, never on a diff against a cache generated by a different
script. A cross-cache comparison of this same change showed +$7,544 of which
only ~$2,500 was the cap — the rest was engine drift between the two caches.

argv: <on|off>   on = cap shorts at 1 (live), off = pre-Sep-2 behaviour
"""
import sys, datetime as _dt
sys.path.insert(0, '/Users/sushil/trading')
import pandas as pd
import futures.sim_replay as srp

MODE = sys.argv[1]
OUT  = '/Users/sushil/trading/futures/factory'
srp.GRADUATED_RVOL = True; srp.RVOL_GRAD_FLOOR = 0.70; srp.REGIME_AWARE_EXITS = True
srp.NO_OVN_SKIP = True; srp.REV_EXIT = (2, 0.30, 120.0); srp.PARTIAL_TAKE_PTS = 150.0
srp.MAX_DAILY_TRADES = 5; srp.HERO_GATE_ENABLED = True; srp.BASE_STOP_PTS = 200.0
srp.SHORT_MAX_CONTRACTS = 1 if MODE == 'on' else None

ab    = srp.load_bars('MNQ', start='2021-02-11', end='2026-08-18')
rth   = srp.filter_ny_session(ab)
dates = sorted(d for d in set(rth.index.date) if d >= _dt.date(2021, 6, 1))
r  = srp._run_scenario(ab, dates, False, False, 'NY', verbose=False)
df = r['df'].copy()
df.to_csv(f'{OUT}/_capab_{MODE}.csv', index=False)
y = pd.to_datetime(df['date'].astype(str)).dt.year
daily = df.groupby('date').pnl.sum(); eq = daily.cumsum()
print(f'CAP={MODE}  n={len(df)}  short2c={int(((df.side=="SHORT")&(df.contracts==2)).sum())}  '
      f'total={df.pnl.sum():+,.0f}  maxDD={(eq-eq.cummax()).min():+,.0f}  worstDay={daily.min():+,.0f}',
      flush=True)
print('  per year: ' + ' '.join(f'{a}:{df.loc[y==a,"pnl"].sum():+,.0f}' for a in sorted(y.unique())), flush=True)
